POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RVc2VyTmFtZTEwIiwiaWQiOiI2M2VhMDIwZmZhNDhiMjhkMGY1ZGIyMGIiLCJpYXQiOjE2NzYyODE4ODZ9.qF8ptttFqitHgU9SyiKtGjCTBm8EWCpJUu9FPhGhO5U

{
    "title": "Ut egestas lorem eu accumsan tempor",
    "author": "vitae tristique",
    "url": "test.com",
    "likes": 16
}