POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjYzZTU0YmRiZDZmZTlhNThjZDYzNDk1NSIsImlhdCI6MTY3NTk3MTU0N30.Lg-LvyzkjR4BVGGbEe4tbx1oj66yNyurxusPwT75alY

{
    "title": "Test Blog1N3",
    "author": "Test Author1N3",
    "url": "TestURL1N3",
    "likes": 2
}