DELETE http://localhost:3003/api/blogs/63e52448011a843659ee4b7d
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1sdXVra2FpIiwiaWQiOiI2M2U1MWFlOTdiOGVkNDU3MzU4OGM0OWMiLCJpYXQiOjE2NzU5NTk1MDZ9.GGxyd1Oj1KuI6glfVVlcz6iPD53Gry28tIH8FjEFROw